### ISSUE TITLE
Geração de vários boletos ao clicar em pagar

### ISSUE THREAD

**Issue by odirlon** [paghiper/woocommerce-paghiper#1]
Oi, show de bola o plugin! 

Amigo notei um comportamento estranho. Quando gero a compra no boleto e finalizo a compra, ele vai para a página para clicar no botão e gerar o boleto. O link do boleto fica assim:

http://projetos.meusite.com/paghiper/wc_order_5925ea74d5686

Ali visualizo o boleto e seus dados perfeitamente. No painel do PagHiper ele gera um boleto. Então fui na página Minha Conta > Pedidos > Ver > e cliquei no link de pagar boleto. Ele gerou outra url e no painel do PagHiper gerou outro boleto sobre o mesmo pedido... 

Acho que isso pode gerar uma confusão muito grande numa grande quantidade de pedidos. Porém gostaria de saber se esse comportamento você previu e se é isso mesmo que vc pretendia. 

Grande abraço.

Arrumei as traduções como te mando?

**Comment by gminarello** [comment]
Estou com o mesmo problema do amigo acima, instalei no WooCommerce e funcionou, porém está gerando um boleto a cada click que o usuário dá nos emails que recebe, e com isso ele passa a receber diversos emails de lembretes de vencimento, gerando confusão.

Sem contar que quando o pedido já está pago, e por algum motivo o PagHiper gera outro boleto para aquele mesmo pedido, o status se altera sozinho de "Processando" para "Aguardando"...

Abraços!

**Comment by henriqueccruz** [comment]
Olá @odirlon, estamos trabalhando em uma solução de re-emissão de boletos, ao invés de gerar um novo sempre que o usuário clica no boleto. Isso deve facilitar a administração dentro do painel da PagHiper, mas não muita coisa em relação à loja. Devemos ter isso pronto na próxima semana.

Isso só causa problemas se você deixar a opção "Enviar e-mail para o comprador" ativada no painel da PagHiper. Essa configuração pode ser alterada no caminho abaixo:
Ferramentas > Notificações > Enviar e-mail para o comprador

O plugin do Woocommerce ja se encarrega das notificações, então é melhor deixar essa opção desativada no painel da PagHiper.

**Comment by henriqueccruz** [comment]
Sobre esse problema do plugin "retirar" o status e reabrir o pedido para pagamento, é um bug e consegui reproduzir sem dificuldades.
Acompanhe a evolução do ticket, @gminarello.

**Comment by odirlon** [comment]
@henriqueccruz Show de bola Henrique, obrigado pelo retorno.
Quanto a configuração eu tinha desabilitado o envio pelo paghiper para usar apenas as notificações do Woocommerce mesmo. Igual você mencionou ali.

Muito obrigado pelo retorno, vou acompanhar a evoluçlão do plugin. 

Você pretende disponibilizar no repositório oficial?

**Comment by gminarello** [comment]
@henriqueccruz fiz os testes aqui porém quando desativo o envio de email para os compradores no painel do PagHiper, e o cliente faz uma compra em meu site através do boleto, o WooCommerce não está enviando os emails. Apenas quando a compra é feita pelo PagSeguro, que o email é enviado. Quando desativo o PagHiper, os emails voltam ao normal. Sabe o que pode ser?

**Comment by gminarello** [comment]
@henriqueccruz estou utilizando o aplicativo SMTP Mailer para cadastro de uma conta SMTP que fica encarregada de enviar os emails da loja. Não testei a versão 1.2, mas na primeira, quando era desativada no painel a opção de enviar email aos clientes, o WooCommerce também não enviava.

**Comment by henriqueccruz** [comment]
@gminarello, seu problema com e-mails ainda persiste? Gostaria de investigar.

**Comment by gminarello** [comment]
@henriqueccruz por não ter conseguido resolver o problema na primeira versão, acabei abandonando o PagHiper pois não conseguia organizar os pedidos com esses erros, assim que fizer a instalação em outro ecommerce, volto com o feedback

**Comment by henriqueccruz** [comment]
@odirlon, vamos enviar ao repositório oficial sim! Deixamos em testes por algum tempo e estamos aguardando análise da equipe Woocommerce/Wordpress. A próxima versão ja re-utiliza os boletos emitidos que estejam dentro da data de vencimento.

@gminarello, só confirmando, o problema que você encontrou é que o cliente não recebia os e-mails do plug-in, referentes ao vencimento do boleto? Se sim, passa pra mim a versão do Wordpress e do Woocommerce utilizadas. Vou tentar replicar o problema.

**Comment by odirlon** [comment]
Você possui outros plugins para teste?

**Comment by gminarello** [comment]
@henriqueccruz na verdade foi um problema crônico que acabei descobrindo os outros. O primeiro problema é que quando ativo a opção de enviar email aos clientes, o email do PagHiper substituía o email do WooCommerce, com isso, se o cliente abrisse o boleto na página de finalização de compra, ele gerava um boleto, e se posteriormente ele clicasse no link do email enviado pelo PagHiper, ele gerava outro boleto. Se o cliente pagasse um dos boletos gerados, e o outro boleto vencesse, ele cancelava o pedido, alterando o status do pedido de PAGO para CANCELADO.

Quando desativei a função de enviar email, ele simplesmente parou de enviar os emails de confirmação de compra, quando a compra era feita no boleto.

Estou utilizando as últimas versões do WordPress e do WooCommerce.

**Comment by henriqueccruz** [comment]
@gminarello Sim, existia um problema em que um boleto pago podia ser marcado como Pendente ou Cancelado. Isso foi corrigido e ja liberado nas versões públicas.

Sobre os e-mails, a opção que você desativou foi dentro da configuração do plug-in ou dentro do Painel da PagHiper?

**Comment by henriqueccruz** [comment]
@odirlon O plug-in vem sendo atualizado no repositório do GitHub conforme bugs e melhorias são lançadas. Temos algumas melhorias preparadas para o lançamento do plug-in no repositório oficial. Você ainda encontra problemas no uso do plug-in?

**Comment by odirlon** [comment]
Vou atualizar hoje para testar, vi nas atualizações que vc fez um comentário do que reportei, dai te passo aqui. Pensei que vc trabalhava em outros plugins e queria testar mesmo pra poder colaborar de alguma forma.

**Comment by odirlon** [comment]
Oi @henriqueccruz, testei o plugin com as atualizações, o mesmo comportamento ainda está acontecendo. 
não sei se é pelo plugin ou o paghiper. 
![pagamento](https://user-images.githubusercontent.com/9590863/29006624-bb31212e-7ac9-11e7-8e77-1f97a0befc31.JPG)

A cada clique para exibir o boleto gera um novo boleto no sistema do paghiper.

**Comment by henriqueccruz** [comment]
@gminarello Acabamos de lançar uma versão que aborda essa questão dos e-mails.
Realmente era um bug e foi corrigido.

@odirlon Atualizo esse ticket assim que abordar pra versão 1.3, que re-utiliza os boletos e envia lembretes de vencimento com um dia de antecedência. Um dia ou dois, no máximo.

**Comment by henriqueccruz** [comment]
Olá pessoal, implementamos isso com sucesso na versão 1.2.5.
Por favor atualizem e abram novo ticket caso tenham problemas.
