### ISSUE TITLE
Paghiper parou de emitir boletos

### ISSUE THREAD

**Issue by Arterraturismo** [paghiper/woocommerce-paghiper#11]
Há dois dias o Paghiper não emite mais boletos, aparece uma página para preencher dados mas não finaliza o pedido. 

Wordpress: 4.7.9
Woocommerce 3.0.9

![image](https://user-images.githubusercontent.com/36677419/36448035-02fdcfca-1665-11e8-8fb4-42b3834f00cd.png)

**Comment by henriqueccruz** [comment]
Olá @Arterraturismo, checa se o cadastro em questão está com o CPF preenchido e se é válido.
Também vale a pena checar se sua conta PagHiper está verificada.

Caso tenha algum detalhe extra, atualize este ticket por favor.

**Comment by henriqueccruz** [comment]
Só confirmando, caso não tenha instalado, esse plugin se integra com o "WooCommerce Extra Checkout Fields for Brazil", do Claudio Sanches. É padrão e ja implementa uma série de campos necessários para se operar um e-commerce no Brasil.

Efetue a instalação dele e preencha o CPF no momento da compra. O CPF não deve mais ser solicitado pela PagHiper depois disso.

Além disso, lançamos a versão 1.2.5 hoje, por favor atualize pelo seu painel de plug-ins.
