### ISSUE TITLE
Cancelamento duplicado dando entrada duplicada no estoque.

### ISSUE THREAD

**Issue by odirlon** [paghiper/woocommerce-paghiper#12]
![image](https://user-images.githubusercontent.com/9590863/37282453-392c5efe-25d3-11e8-9f65-b96ed7014f02.png)

Olá, por algum motivo o boleto cancelou duas vezes e deu entrada duplicada no estoque. O que pode ser?

**Comment by odirlon** [comment]
Verifiquei e a versão do plugin é a ultima.

**Comment by henriqueccruz** [comment]
Olá @odirlon, lançamos hoje a versão 1.2.5 que corrige esse problema e introduz uma série de melhorias. A atualização ja deve estar disponível pelo seu painel de plug-ins.
