### ISSUE TITLE
Issue with woocommerce

### ISSUE THREAD

**Issue by redsparkers** [paghiper/woocommerce-paghiper#13]
Hello, 
I have one site with wocommerce (Version 3.3.5).then  Installed the WooCommerce Boleto PagHiper (Version 1.2.5 ). after checkout summery  when i click on "Pay the ticket'.  i am getting the error Warning: reset() expects parameter 1 to be array, null given
Refer the attachment - 1. checkout-success.png for the order summery
                                     2. wc_order_5acef61a92d26.png
![checkout-success](https://user-images.githubusercontent.com/35765884/38659340-c5dd8acc-3e46-11e8-9b33-f053f6a702b8.png)
![wc_order_5acef61a92d26](https://user-images.githubusercontent.com/35765884/38659345-c7667610-3e46-11e8-97bd-701b39570a1e.png)

**Comment by henriqueccruz** [comment]
Hi there, @redsparkers. I couldn't reproduce your issue. Can you tell me what steps did you take to get to that error?
Also, did you check your credentials and token on the config screen?
I'll be able to assist you once you provide me with more info.
