### ISSUE TITLE
Ao clicar em pagar boleto - Not Found

### ISSUE THREAD

**Issue by allanqm** [paghiper/woocommerce-paghiper#14]
Após realizar o checkout e clicar em "Pagar o boleto, o site é redirecionado para o endereço http://18.219.47.47/paghiper/wc_order_5afb497a41c5b e o seguinte erro é exibido:

> Not Found
> 
> The requested URL /paghiper/wc_order_5afb497a41c5b was not found on this server.
> 
> Apache/2.4.18 (Ubuntu) Server at 18.219.47.47 Port 80

Como posso resolver este erro?

**Comment by allanqm** [comment]
Woocommerce Versão 3.3.5 
WooCommerce Boleto PagHiper Versão 1.2.5.3
WooCommerce Extra Checkout Fields for Brazil Versão 3.6.0
WordPress 4.9.5 com o tema Fury.

**Comment by allanqm** [comment]
Relatório do Woocommerce

### WordPress Environment ###

Home URL: http://18.219.47.47
Site URL: http://18.219.47.47
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.30-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.22
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Tamanho total do banco de dados: 1.82MB
Tamanho dos dados do banco de dados: 0.94MB
Tamanho do índice do banco de dado: 0.88MB
wp_woocommerce_sessions: Dados: 0.02MB + Índices: 0.02MB
wp_woocommerce_api_keys: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índices: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índices: 0.05MB
wp_woocommerce_order_items: Dados: 0.02MB + Índices: 0.02MB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índices: 0.06MB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índices: 0.00MB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índices: 0.00MB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índices: 0.02MB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índices: 0.03MB
wp_woocommerce_log: Dados: 0.02MB + Índices: 0.02MB
wp_commentmeta: Dados: 0.02MB + Índices: 0.03MB
wp_comments: Dados: 0.02MB + Índices: 0.09MB
wp_links: Dados: 0.02MB + Índices: 0.02MB
wp_options: Dados: 0.33MB + Índices: 0.02MB
wp_postmeta: Dados: 0.06MB + Índices: 0.06MB
wp_posts: Dados: 0.05MB + Índices: 0.06MB
wp_termmeta: Dados: 0.02MB + Índices: 0.03MB
wp_terms: Dados: 0.02MB + Índices: 0.03MB
wp_term_relationships: Dados: 0.02MB + Índices: 0.02MB
wp_term_taxonomy: Dados: 0.02MB + Índices: 0.03MB
wp_usermeta: Dados: 0.02MB + Índices: 0.03MB
wp_users: Dados: 0.02MB + Índices: 0.05MB
wp_wc_download_log: Dados: 0.02MB + Índices: 0.03MB
wp_wc_webhooks: Dados: 0.02MB + Índices: 0.02MB

### Post Type Counts ###

attachment: 10
customize_changeset: 2
page: 16
post: 3
product: 1
revision: 8
shop_order: 8

### Security ###

Secure connection (HTTPS): ❌Sua loja não está usando HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (6) ###

WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0 – Não testado com a versão ativa do WooCommerce
Boleto Facil - WooCommerce Gateway: por BoletoBancario.com – 1.1 – Não testado com a versão ativa do WooCommerce
Fury Blocks: por Theme Vision – 1.0.1
Fury Core: por Theme Vision – 1.0.1
WooCommerce Boleto PagHiper: por Henrique Cruz
PagHiper – 1.2.5.3 – Não testado com a versão ativa do WooCommerce

WooCommerce: por Automattic – 3.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base da loja: #2 - /index.php/sample-page/
Carrinho: #34 - /index.php/carrinho/
Finalizar compra: #37 - /index.php/checkout/
Minha conta: #39 - /index.php/conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Fury
Version: 1.0.8
Author URL: http://theme-vision.com/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: fury/woocommerce/cart/cart-item-data.php
fury/woocommerce/cart/cart-totals.php
fury/woocommerce/cart/cart.php
fury/woocommerce/cart/proceed-to-checkout-button.php
fury/woocommerce/cart/shipping-calculator.php
fury/woocommerce/checkout/form-billing.php
fury/woocommerce/checkout/form-checkout.php
fury/woocommerce/checkout/form-coupon.php
fury/woocommerce/checkout/form-shipping.php
fury/woocommerce/checkout/payment-method.php
fury/woocommerce/checkout/payment.php
fury/woocommerce/checkout/review-order.php
fury/woocommerce/checkout/thankyou.php
fury/woocommerce/content-product.php
fury/woocommerce/content-product_cat.php
fury/woocommerce/content-single-product.php
fury/woocommerce/global/quantity-input.php
fury/woocommerce/loop/add-to-cart.php
fury/woocommerce/loop/loop-end.php
fury/woocommerce/loop/loop-start.php
fury/woocommerce/loop/pagination.php
fury/woocommerce/loop/price.php
fury/woocommerce/loop/sale-flash.php
fury/woocommerce/myaccount/dashboard.php
fury/woocommerce/myaccount/form-edit-account.php
fury/woocommerce/myaccount/form-edit-address.php
fury/woocommerce/myaccount/form-login.php
fury/woocommerce/myaccount/form-lost-password.php
fury/woocommerce/myaccount/my-account.php
fury/woocommerce/myaccount/my-address.php
fury/woocommerce/myaccount/my-orders.php
fury/woocommerce/myaccount/navigation.php
fury/woocommerce/myaccount/orders.php
fury/woocommerce/order/order-details.php
fury/woocommerce/order/order-downloads.php
fury/product-searchform.php versão - está desatualizado. A versão do core é 3.3.0
fury/woocommerce/single-product/add-to-cart/simple.php
fury/woocommerce/single-product/add-to-cart/variable.php
fury/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
fury/woocommerce/single-product/add-to-cart/variation.php
fury/woocommerce/single-product/meta.php
fury/woocommerce/single-product/price.php
fury/woocommerce/single-product/product-attributes.php
fury/woocommerce/single-product/product-image.php
fury/woocommerce/single-product/product-thumbnails.php
fury/woocommerce/single-product/review.php
fury/woocommerce/single-product/sale-flash.php
fury/woocommerce/single-product/tabs/additional-information.php
fury/woocommerce/single-product/tabs/description.php
fury/woocommerce/single-product/tabs/tabs.php
fury/woocommerce/single-product/title.php
fury/woocommerce/single-product-reviews.php
fury/woocommerce/single-product.php

Outdated Templates: ❌Aprenda como atualizar
`

**Comment by fgsants** [comment]
Mesma coisa aqui, no meu caso o site fica em branco após clicar em "Pagar o boleto"

**Comment by henriqueccruz** [comment]
@fgsants, seu problema ainda persiste?
Prestamos suporte ao Allan por outro canal de comunicação, não está conectado ao erro que aparece na sua loja.

**Comment by fgsants** [comment]
Olá @henriqueccruz, fiz a correção que vc passou lá e consegui acessar as configurações do módulo normalmente depois, obrigado.

**Comment by henriqueccruz** [comment]
Acabei de fazer uma modificação no plug-in que corrige essa questão da tela em branco.
Se tiver dificuldades, por favor abra outro ticket para acompanharmos.
Obrigado.
