### ISSUE TITLE
Paghiper não funciona no woocommerce

### ISSUE THREAD

**Issue by priscilaribeiro** [paghiper/woocommerce-paghiper#15]
Impossível abrir boleto após clicar em visualizar. Direciona para página em branco! Alguma previsão de voltar a funcionar?

**Comment by henriqueccruz** [comment]
Boa tarde, @priscilaneu.
Nos ajude a entender melhor o problema. Consegue ativar WP_DEBUG no arquivo wp-config.php e acessar o boleto novamente?

Se sim, cole aqui a mensagem de erro por favor.

**Comment by priscilaneu** [comment]
Warning: reset() expects parameter 1 to be array, null given in /home/bybfashions/www/wp-content/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php on line 93

**Comment by priscilaneu** [comment]
Notice: woocommerce_get_order_id_by_order_key está obsoleto desde a versão 3.0! Use wc_get_order_id_by_order_key em seu lugar. in /home/bybfashions/www/wp-includes/functions.php on line 3840

Notice: billing_first_name foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_last_name foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_address_1 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_address_2 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_city foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_state foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_postcode foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_country foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: order_date foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: Undefined variable: different_due_date in /home/bybfashions/www/wp-content/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php on line 140

Notice: Undefined variable: different_due_date in /home/bybfashions/www/wp-content/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php on line 158

Notice: Undefined variable: different_total in /home/bybfashions/www/wp-content/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php on line 158

Notice: id foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: order_date foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_email foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_address_1 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_number foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_address_2 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_neighborhood foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_city foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: billing_state foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce-paghiper-master/includes/views/html-boleto.php'), include('/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/bybfashions/www/wp-includes/functions.php on line 4148

Notice: WC_Customer::get_postcode está obsoleto desde a versão 3.0! Use WC_Customer::get_billing_postcode em seu lugar. in /home/bybfashions/www/wp-includes/functions.php on line 3840

Notice: Undefined index: cpf in /home/bybfashions/www/wp-content/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php on line 58

Warning: reset() expects parameter 1 to be array, null given in /home/bybfashions/www/wp-content/plugins/woocommerce-paghiper-master/includes/paghiper/layout.php on line 93

**Comment by henriqueccruz** [comment]
@priscilaneu, consegue pegar uma versão nova do plug-in e atualizar na sua instalação do Woocommerce?
Efetuei uma pequena modificação que aborda esse problema.

**Comment by priscilaneu** [comment]
Quase... agora ele gera, mas retorna uma página assim:
{"transacao":[{"idTransacao":"D3R2TSSYGPK9WL30","dataTransacao":"2018-06-08 18:28:59","valorTotal":"178.70","status":"aguardando","idPlataforma":"1886","urlPagamento":"https://www.paghiper.com/checkout/boleto/3c0bc06e5bde9a7466db54f6290c639aaab7cb866dbf6e54bb252b961b5e9c9fa65cdd6b7725f5753c33ca8c90fefd15d42fc3f609a631b6c4baebaa8eaaeaca/D3R2TSSYGPK9WL30/80302870","urlPdfPagamento":"https://www.paghiper.com/checkout/boleto/3c0bc06e5bde9a7466db54f6290c639aaab7cb866dbf6e54bb252b961b5e9c9fa65cdd6b7725f5753c33ca8c90fefd15d42fc3f609a631b6c4baebaa8eaaeaca/D3R2TSSYGPK9WL30/80302870/pdf","linhaDigitavel":"03399.87836 48900.000802 30287.001017 8 75540000017870","dataVencimento":"2018-06-13"}]}

url: https://www.paghiper.com/checkout/emissaoBoleto/9ZFHH

E não gera o boleto!

**Comment by priscilaneu** [comment]
Retificando, o boleto é gerado, mas retorna as informações desse boleto em json, em vez de direcionar para url de pagamento, pois se eu copio e colo essa url no navegador, o boleto aparece.

**Comment by henriqueccruz** [comment]
No arquivo /woocommerce-paghiper/includes/paghiper/layout.php, na linha 93, substitui 
`if(!$output) {` por
`if(!is_array($output)) {` por gentileza. Veja se agora seu boleto é retornado normalmente.

**Comment by priscilaneu** [comment]
Não funcionou, está mostrando a mesma coisa...

{"transacao":[{"idTransacao":"BTXJSYGKSIF34H7G","dataTransacao":"2018-06-09 21:11:41","valorTotal":"320.10","status":"aguardando","idPlataforma":"1888","urlPagamento":"https://www.paghiper.com/checkout/boleto/61b9c239a0924eb1f8a7d9a00a71ccb538a06f6b185f14ceeff9514b3e172777ae5e4abe598c8e59e7b3acd2baf3a6816aac7cb48ab8a2a9a9e70fbd0b8f8335/BTXJSYGKSIF34H7G/35409361","urlPdfPagamento":"https://www.paghiper.com/checkout/boleto/61b9c239a0924eb1f8a7d9a00a71ccb538a06f6b185f14ceeff9514b3e172777ae5e4abe598c8e59e7b3acd2baf3a6816aac7cb48ab8a2a9a9e70fbd0b8f8335/BTXJSYGKSIF34H7G/35409361/pdf","linhaDigitavel":"03399.87836 48900.000356 40936.101019 8 75550000032010","dataVencimento":"2018-06-14"}]}

**Comment by henriqueccruz** [comment]
Entendo.
@priscilaneu, consegue checar se seu PHP foi compilado com suporte a JSON?
Você consegue chegar isso criando um arquivo PHP com a função phpinfo(); dentro.

Estou implementando algumas checagens no plug-in pra facilitar esse tipo de diagnóstico, mas minha idéia era fazermos sua integração funcionar perfeitamente antes da próxima atualização.

**Comment by henriqueccruz** [comment]
Também seria legal saber a versão dos seguintes itens e componentes:
Wordpress
Woocommerce
PHP ativo na instalação da loja
Plug-in da PagHiper (que suponho ser a última versão)

**Comment by priscilaneu** [comment]
Bom dia,

Na verdade esse arquivo já existe no wordpress, só não sei onde eu verifico
a informação!

Versões:
PHP 5.6
Wordpress: 4.9.6
Woocommerce: última versão, atualziado na quinta, mas antes disso já não
funcionava.
PagHiper, excluí plugin anterior e instalei o novo que peguei no git na
sexta feira.

Em 11 de junho de 2018 01:43, Henrique Cruz <notifications@github.com>
escreveu:

**Comment by fgsants** [comment]
Complementando no erro, acontece a mesma coisa aqui após atualizar a versão do plugin. No meu caso PHP 7.0, JSON, e campo CPF habilitado . Tentei também com e sem o modo transparente e dá a mesma coisa. Nada no log do PHP.

**Comment by henriqueccruz** [comment]
@fgsants, como você está fazendo pra incluir o campo de CPF no checkout?
Além disso (caso esteja usando o plugin Extra Checkout Fields for Brazil), o campo de "Exibir Tipo de Pessoa" está marcado como "Nenhuma"?

Estamos implementando alguns metodos que eliminem a dependência desse plug-in, para permitir mais flexibilidade no checkout. Seu feedback também é importante, @priscilaneu.

**Comment by priscilaneu** [comment]
Olá, com a última passada, ao adicionar aquele plugin adicional, funcionou
corretamente! Obrigada pelo suporte!!!



Em 15 de junho de 2018 16:51, Henrique Cruz <notifications@github.com>
escreveu:

**Comment by gascon07** [comment]
Hoje tive esse problema no Woocommerce de não conseguir gerar o boleto e vim aqui para saber o que era e me deparei com essa discussão. Na minha loja em "Extra Checkout Fields for Brazil" a opção "Exibir Tipo de Pessoa" está marcado como "Nenhuma", ai troquei para "Pessoa Física" e voltou a gerar os boletos. Aguardando também a independência do Extra Checkout Fields for Brazil. 

Mesmo assim vim agradecer que resolvi!

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
