### ISSUE TITLE
É necessário clicar em pagar boleto para que o mesmo seja gerado?

### ISSUE THREAD

**Issue by wagnerjaccoud** [paghiper/woocommerce-paghiper#16]
Olá, tenho uma dúvida que tem acontecido em meu site.
Ao escolher boleto como forma de pagamento no site, o cliente finaliza o checkout com esta opção. 
Após é direcionado para a página de confirmação do pedido. Porém, o boleto só será gerado caso o cliente clique em pagar boleto, caso contrário o pedido fica como aguardando pagamento e o boleto não é gerado.

Teria alguma possibilidade de ao finalizar a compra o boleto já fosse gerado e enviado para o e-mail do cliente sem a necessidade de clicar em PAGAR Boleto?

Mais um detalhe que esqueci de mencionar. A opção de restaurar estoque em meu site ao pedido ser cancelado ele só retorna o estoque o primeiro produto da lista. Como trabalho com muitas variações tive que desativar a opção de restaurar, mas mesmo assim o plugin permanece restaurando o estoque.

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
