### ISSUE TITLE
"Visualizar boleto" no resumo do pedido sumiu

### ISSUE THREAD

**Issue by fgsants** [paghiper/woocommerce-paghiper#18]
Olá, desde que atualizei para a versão mais recente do WooCommerce a mensagem para visualizar o boleto na página de resumo do pedido não está aparecendo mais.

Dei uma olhada no log PHP e está tudo ok por lá. Também chequei o código fonte da página e não tem nada oculto também. 

Será que algum hook que vc estava usando para imprimir esta mensagem foi alterada na versão mais recente do WC? Dei uma olhada no changelog deles mas não achei nada que apontasse para isso.

Também percebi que ele não está puxando mais o CPF/CNPJ cadastrado do cliente, pedindo ele novamente na página para gerar o boleto (link no email e "minha conta")

**Comment by henriqueccruz** [comment]
Olá @fgsants, não vi seu ticket, desculpe.
O problema ainda persiste? Qual versão do plugin está usando?

Sua loja usa o plug-in "WooCommerce Extra Checkout Fields for Brazil"?

**Comment by fgsants** [comment]
Olá @henriqueccruz, usa sim. Caso necessário posso criar uma instalação nova para fazer mais debug.

**Comment by henriqueccruz** [comment]
Me fala qual versão do WP e do Woocommerce está utilizando, por favor. Vou tentar replicar seu problema.

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
