### ISSUE TITLE
Assunto sobre Taxa

### ISSUE THREAD

**Issue by MultXOficial** [paghiper/woocommerce-paghiper#21]
Olá, gostaria de tirar uma duvida, o PAGHIPER cobra uma taxa de 1,85 por boleto quando o cliente efetua o pagamento correto?

Porem com a instalação no PAGHIPER gostaria de saber se tem a possibilidade de passar essa taxa para os clientes que queiram usar o meio de pagamento BOLETO do PAGHIPER no WooCommerce.

Infelizmente nas configurações do próprio PAGHIPER não encontrei essa função. Alguém sabe algum meio? Que eu não tenha olhado?

Aguardo retorno e agradeço pela atenção de todos que puderem ajudar!

**Comment by henriqueccruz** [comment]
É possível sim, usando soluções como "Payment Gateway Based Fees" ou desenvolvendo filtros pra modificar o valor no envio do pedido.
