### ISSUE TITLE
IMPRIMIR BOLETO saindo desconfigurado

### ISSUE THREAD

**Issue by rdg2001** [paghiper/woocommerce-paghiper#22]
Boleto desconfigurado pela opção IMPRIMIR BOLETO no html gerado apos pedido feito.
Se usar direto o CRTL+P sai ok, ou via PDF ok. 

Usando a versao 1.2.6.1

Imagem de como esta saindo: https://uploaddeimagens.com.br/imagens/boleto-desconfigurado-jpg
Link para teste: https://www.enatural.com.br/paghiper/wc_order_5c2ce0635a10b

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
