### ISSUE TITLE
CSS nao encontrado gerando erro 404

### ISSUE THREAD

**Issue by rdg2001** [paghiper/woocommerce-paghiper#23]
O html que gera o boleto busca por um CSS localmente na loja e nao encontra. Testei e o CSS esta no servidor do PAGHIPER. 

Procura <link rel="stylesheet" href="/checkout/santander/resources/lib/font-awesome/css/font-awesome.css">

O mesmo esta em: http://paghiper.com/checkout/santander/resources/lib/font-awesome/css/font-awesome.css

Imagem do codigo no HTML:  https://uploaddeimagens.com.br/imagens/css_nao_encontrado-jpg/mostrar-codigo
Imagem do erro 404 na loja:  https://uploaddeimagens.com.br/imagens/404-jpg-e74751a8-d36d-4b66-acde-cce9b52ea523/mostrar-codigo

Usando a versao 1.2.6.1

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
