### ISSUE TITLE
Não gera o boleto

### ISSUE THREAD

**Issue by adaumhenrique** [paghiper/woocommerce-paghiper#24]
Estou usando a versão do plugin 1.2.6.1
Woocommerce 3.5.4
Plugin extra checkout fields habilitado.
Debug habilitado
Ele exibe as seguintes mensagens de erro:
Notice: Undefined index: debug in /home/inovapap/public_html/wp-content/plugins/woo-boleto-paghiper/includes/wc-retorno-paghiper.php on line 7

Notice: woocommerce_get_order_id_by_order_key está obsoleto desde a versão 3.0! Use wc_get_order_id_by_order_key em seu lugar. in /home/inovapap/public_html/wp-includes/functions.php on line 3923

Notice: billing_cnpj foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_first_name foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_last_name foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_address_1 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_address_2 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_city foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_state foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_postcode foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_country foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: Undefined index: number in /home/inovapap/public_html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 478

Notice: Undefined index: neighborhood in /home/inovapap/public_html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil/includes/class-extra-checkout-fields-for-brazil-front-end.php on line 479

Notice: billing_persontype foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_cpf foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_persontype foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: order_date foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: Undefined variable: different_due_date in /home/inovapap/public_html/wp-content/plugins/woo-boleto-paghiper/includes/paghiper/layout.php on line 51

Notice: Undefined variable: different_total in /home/inovapap/public_html/wp-content/plugins/woo-boleto-paghiper/includes/paghiper/layout.php on line 84

Notice: id foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: order_date foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_email foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_address_1 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_number foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_address_2 foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_neighborhood foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_city foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: billing_state foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woo-boleto-paghiper/includes/views/html-boleto.php'), include('/plugins/woo-boleto-paghiper/includes/paghiper/layout.php'), httpPost, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/inovapap/public_html/wp-includes/functions.php on line 4231

Notice: WC_Customer::get_postcode está obsoleto desde a versão 3.0! Use WC_Customer::get_billing_postcode em seu lugar. in /home/inovapap/public_html/wp-includes/functions.php on line 3923

**Comment by henriqueccruz** [comment]
@adaumhenrique, checa nos logs do Woocommerce o motivo do boleto não estar sendo emitido.
O log anexado aqui só contem notices, que não representam erros.
Checa em Woocommerce > Status > Logs

**Comment by henriqueccruz** [comment]
Qual versão do plug-in você está usando?
Checa nas configurações do plugin se ativou "Log de depuração". Se ainda não tiver ativado, faça isso e emita outro boleto. Isso vai gravar as informações de log e conseguiremos saber o que ocorreu para impedir a criação do boleto.

**Comment by adaumhenrique** [comment]
O log retorna:
01-23-2019 @ 17:01:57 - Pedido #845: Data de vencimento não presente no banco.
01-23-2019 @ 17:02:00 - Erro: Boleto retornou checkout comum ao invés de boleto. Verifique se seu checkout está solicitando CPF ou CNPJ do cliente. Pedido: #845

Obs: o plugin extra checkout fields for brazil está ativado e está sendo preenchido o CPF e tipo de pessoa do cliente normalmente.

**Comment by henriqueccruz** [comment]
Qual versão do plug-in está utilizando?
Além disso, está enfrentando problemas com um pedido/cliente específico ou geral?

**Comment by adaumhenrique** [comment]
A versão mais recente 1.2.6.1
Na versão anterior 1.2.5 já estava dando problema por isso atualizei
Qualquer pedido, geral.

**Comment by henriqueccruz** [comment]
Vou verificar e tentar replicar.Qual versão do WordPress, Woocommerce e tema utilizados?Em 23 de jan de 2019 10:44 PM, Adam Silva <notifications@github.com> escreveu:A versão mais recente 1.2.6.1

Na versão anterior 1.2.5 já estava dando problema por isso atualizei

Qualquer pedido, geral.

**Comment by adaumhenrique** [comment]
Woocommerce 3.5.4
WP 5.0.3
Template Flatsome 3.7.2
Tudo na versão mais recente.

**Comment by adaumhenrique** [comment]
Pessoa física e pessoa jurídica.
Está pedindo CPF sim, no caso os testes que eu fiz foi como pessoa física, porém a loja precisa da pessoa jurídica também.

**Comment by adaumhenrique** [comment]
Algum avanço?

**Comment by henriqueccruz** [comment]
Sim, temos uma update em curso para o início da semana que vem.
Atualizo este ticket assim que a versão estiver disponível para download.

**Comment by adaumhenrique** [comment]
OK, obrigado, fico no aguardo.

**Comment by adaumhenrique** [comment]
Alguma novidade?

**Comment by jsteruya** [comment]
Olá hoje dia 13/05 estou com o mesmo problema que o @adaumhenrique 

Paghiper : Versão 1.2.6.1  
Woocommerce : Versão 3.6.2
Wordpress : Versão 5.2
Tema : GreenfarmVersão: 1.0.5

05-13-2019 @ 10:11:20 - Pedido #3785: Data de vencimento não presente no banco.
05-13-2019 @ 10:11:20 - Erro: Boleto retornou checkout comum ao invés de boleto. Verifique se seu checkout está solicitando CPF ou CNPJ do cliente. Pedido: #3785

Extra Checkout Fields está configurado corretamente também.

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
