### ISSUE TITLE
Não atualiza Status Woocommerce

### ISSUE THREAD

**Issue by danimarw** [paghiper/woocommerce-paghiper#25]
Bom dia galera, estou com um problema com o módulo no Woocommerce. A geração do boleto, impressão ocorre tudo corretamente, porém quando o pagamento do boleto é aprovado, no woocommerce fica como aguardando:

Boleto PagHiper: Aguardando cliente acessar o boleto. Status do pedido alterado de Pagamento pendente para Aguardando.

Ele não atualiza para Processando e muito menos coloca uma nota de pagamento aprovado, é normal isso? o Módulo não tem essa função ou algo de errado não está certo? rsrsr

**Comment by henriqueccruz** [comment]
Olá @danimarw.
Sim, o plugin tem a funcionalidade e deveria atualizar o status normalmente.
Se importa de compartilhar a URL do website pra eu dar uma olhada?

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
