### ISSUE TITLE
[Sugestão] Alterar data de vencimento

### ISSUE THREAD

**Issue by hmaesta** [paghiper/woocommerce-paghiper#29]
O Paghiper oferece a possibilidade de alterar a data de vencimento direto da página do pedido – esse é um diferencial muito interessante e bem-vindo.

Algumas sugestões:
- Alterar o input para `type=date` ao invés de `type=text`, [como é atualmente](https://github.com/paghiper/woocommerce-paghiper/blob/98d615585d2611e9c535c7d2aad4da94e5b464e5/includes/class-wc-paghiper-admin.php#L74). Isso permite abrir o datepicker nativo do navegador e facilitar o processo de escolha de data.
- O campo pede claramente para escolher uma nova data de vencimento, mas ao alterar para a data escolhida, o plugin adiciona os "dias para vencimento" a data – ou seja, a data de vencimento não é exatamente a que eu escolhi.

**Comment by henriqueccruz** [comment]
@hmaesta A update nova implementa validação, formatação e máscara ao campo, facilitando a gestão
Caso tenha problemas com a update, por favor abra um novo  ticket
Além disso, lembre-se de informar seu API key na configuração (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
