### ISSUE TITLE
Re-aproveitamento de boletos emitidos

### ISSUE THREAD

**Issue by henriqueccruz** [paghiper/woocommerce-paghiper#3]
#1 - Planejado para a próxima versão: Reutilizar boletos ja emitidos até a data de vencimento. Gerar novos boletos somente após o cancelamento ou passada a data de vencimento.

**Comment by ediluz1991** [comment]
Quando sai a versão que vai parar com a duplicação de boletos?
eu desativei as notificações do paghiper, isso ajuda a evitar que um pedido pago seja cancelado devido a outro boleto gerado que não foi pago no mesmo pedido?

**Comment by henriqueccruz** [comment]
Olá @ediluz1991, caso você tenha enfrentado problemas com cancelamento de boletos, peço que pegue a versão mais recente do plugin e substitua o plug-in que usa.

Essa versão (1.2.4) corrige isso e ativa atualizações automáticas novamente.

**Comment by ediluz1991** [comment]
Bom dia,

Para atualizar é só substituir todos arquivos do plugin?

Em 10 de outubro de 2017 01:55, henriqueccruz <notifications@github.com>
escreveu:

**Comment by henriqueccruz** [comment]
Sim, isso mesmo @ediluz1991.
Se tiver problemas, basta abrir outro ticket para acompanharmos.

**Comment by ediluz1991** [comment]
Posso ativar os envios de emails do paghiper pro cliente ou não precisa
disso?

2017-10-13 0:44 GMT-03:00 Henrique Cruz <notifications@github.com>:

**Comment by henriqueccruz** [comment]
Implementamos isso na v1.2.5, ja disponível para atualização pelo painel de plug-ins, ou para download e instalação manual.

Caso tenham problemas, por favor abram um novo ticket.
