### ISSUE TITLE
Não gera o boleto

### ISSUE THREAD

**Issue by ediluz1991** [paghiper/woocommerce-paghiper#31]
Ao realizar uma compra não gera o boleto, segue o erro: https://www.meliseflores.com/paghiper/wc_order_qadXrQdtG10S6/

**Comment by leonardola** [comment]
Fiz a reinstalação do plugin com a versão 1.2.6.1 e conferi os dados. Percebi que o email estava incorreto. Agora o boleto está sendo gerado.

**Comment by henriqueccruz** [comment]
Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado! 😁
