### ISSUE TITLE
Cancelamento de Pedidos

### ISSUE THREAD

**Issue by otvb** [paghiper/woocommerce-paghiper#32]
Olá,
O cancelamento de pedidos quando os boletos não são pagos não está funcionando. Eu marquei a opção "Cancelar pedidos quando o boleto expirar?"

No meu caso são 4 dias úteis para vencimento. Entretanto, após os 4 dias os pedidos continuam com o status "Aguardando" e nunca são cancelados.

**Comment by henriqueccruz** [comment]
@otvb Update liberada por aqui (v2.0.1) e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado!
