### ISSUE TITLE
Atualização do plugin

### ISSUE THREAD

**Issue by marcos-alexandre82** [paghiper/woocommerce-paghiper#33]
Olá, espero que estejam bem ;)

Os plugins de segurança relataram que o https://wordpress.org/plugins/woo-boleto-paghiper/ está possivelmente abandonado.

Acredito que nenhuma modificação no código é necessária, mas se você puder alterar as versões testadas, ajudará a não ter dúvidas sobre a segurança do plugin.

Alguma previsão para o lançamento da próxima versão?

Obrigado ;)

**Comment by henriqueccruz** [comment]
Olá @marcos-alexandre82 

Agradecemos pelo ticket. O plug-in definitivamente não está abandonado, temos uma grande atualização em homologação e devemos lançá-la ainda neste mes.
Deixaremos o ticket aberto e te atualizamos assim que estiver disponível.

Obrigado!

**Comment by marcos-alexandre82** [comment]
@henriqueccruz show! Como a última atualização no repositório oficial do WordPress tem mais de 2 anos, ele gera estes avisos. Mas fico feliz em saber que logo termos novidades ;)

Parabéns pelo plugin ;)

**Comment by henriqueccruz** [comment]
@marcos-alexandre82 Update liberada por aqui e também pelo repositório do WP.
Ao atualizar, lembre-se de informar sua API key nas configurações (você pode pegar na tela de credenciais, do seu painel do Paghiper)
Obrigado!
