### ISSUE TITLE
Pedido é registrado no PagHiper apenas se o cliente abrir o link de boleto

### ISSUE THREAD

**Issue by echogit** [paghiper/woocommerce-paghiper#4]
Infelizmente acabei de verificar que da forma como está implementado no momento, o  boleto é registrado no paghiper, passando o pedido para aguardando e enviando os devidos emails, apenas se o link de boleto for aberto na página pós checkout. Isto é inadmissível, uma vez que o cliente pode não abir o link após fechar a compra, e nunca irá receber o email com o link do boleto.

Infelizmente não da para utilizar o plugin desta forma. Aguardo um posicionamento para correção deste bug crítico.

**Comment by henriqueccruz** [comment]
Obrigado por reportar seu problema. A questão foi resolvida na versão mais recente (1.2.1)
Por favor atualize seu plug-in.

[https://github.com/paghiper/woocommerce-paghiper/releases/tag/1.2.1](PagHiper para Woocommerce v1.2.1)
