### ISSUE TITLE
Gerando boleto em outra forma de pagamento sem ser PagHiper

### ISSUE THREAD

**Issue by alexjuniordev** [paghiper/woocommerce-paghiper#41]
Após integração do plugin PagHiper versão 2.1 está acontecendo um problema muito estranho. Está gerando boleto para pedidos que nem são da forma de pagamento boleto. Exemplo, o cliente compra e paga via cartão de crédito (via maxipago, outro plugin), e o sistema pagHiper envia boleto pra ele também depois de uma hora mais ou menos, sozinho.
 
Vocês tem ideia do que possa ser e poderiam nos ajudar? Queremos continuar usando o plugin de vocês junto com o Pix, mas isso nos está causando uma grande confusão com os nossos clientes.

**Comment by henriqueccruz** [comment]
Bom dia @alexjuniordev 
Estamos cientes do problema e ja temos uma correção em andamento.
Sentimos muito pelo transtorno que isso possa ter causado.

Caso precise, você pode reverter o plug-in para a v2.0.5 temporariamente.
Estamos tratando esse problema com prioridade total. Update sai logo menos.

**Comment by alexjuniordev** [comment]
Obrigado pela rápida resposta e atenção @henriqueccruz . Por enquanto estamos informando aos clientes que ignorem o recebimento do boleto. Não queremos tirar a tecnologia pois nessa versão possui a novidade do Pix que até então está funcionando perfeitamente. Então estamos decidindo por esperar essa atualização, o que acha? Obrigado!

**Comment by henriqueccruz** [comment]
Entendo @alexjuniordev . Daremos uma resposta rápida ao problema, então vocês não precisarão esperar muito.
Vou te atualizando por aqui.

**Comment by alexjuniordev** [comment]
Ok @henriqueccruz , muito obrigado novamente

**Comment by henriqueccruz** [comment]
@alexjuniordev 
Update disponível! Dentre várias melhorias, esses boletos gerados indevidamente não vão mais reincidir.
Permanecemos a disposição para te atender.

Seguimos engajados no nosso objetivo, que é fazer deste, o melhor plug-in de boletos (e agora, de PIX) do mercado.
Seu feedback é importantíssimo para seguimos melhorando.
Caso tenha problemas com a nova update, ficamos a sua disposição, só peço a gentileza de abrir outro ticket.

**Comment by alexjuniordev** [comment]
Opa @henriqueccruz , tudo bem? Cara instalei tudo direitinho e até então estava tudo bem. Porém quando algo está impactando diretamente nos produtos. Por incrível que pareça. Com esse plugin ativo eu não consigo editar meus produtos. Se eu desativá-lo eu consigo.

**Comment by alexjuniordev** [comment]
Mais um detalhe é que isso não acontece com a versão 2.1 , então retornei pra ela novamente.

**Comment by henriqueccruz** [comment]
Você notou se isso ocorre em todos os pedidos? Ou somente alguns?Seria legal saber qual versão do Wordpress e do Woocommerce você está usando.Liberaremos um fix pra isso ainda hoje.Em 27 de jan de 2021 09:25, alexjuniordev <notifications@github.com> escreveu:

Mais um detalhe é que isso não acontece com a versão 2.1 , então retornei pra ela novamente.

**Comment by alexjuniordev** [comment]
Oi @henriqueccruz a gente aqui gera boletos e pix em nosso site pelo pagHiper todos os dias. Na verdade quando atualizei o plugin para a nova versão os pedidos continuaram normais. O que impactou foram nos 'produtos'. Após instalar a nova versão e fazer a varredura no site para ver se todas as funcionalidades estavam OK, a funcionalidade de editar e adicionar produtos no site ficou inativa com a mensagem "Há um erro crítico no seu site". Após desinstalar o plugin 2.1.1 da paghiper a funcionalidade voltou ao normal imediatamente. Instalei novamente, a função parou novamente, desinstalei novamente e voltou ao normal novamente. Então instalei a versão anteior do plugin e tudo ficou normal.

**Comment by alexjuniordev** [comment]
Estamos na versão mais atual do wordpress (5.6) e versão 4.8 do Woocommerce
