### ISSUE TITLE
Plugin 2.1.1 impactando diretamente na edição de Produtos do Woocommerce

### ISSUE THREAD

**Issue by alexjuniordev** [paghiper/woocommerce-paghiper#43]
Olá pessoal, a partir desta versão 2.1.1 do plugin, se ativo, não consigo editar/adicionar meus produtos do Woocommerce. Se eu desativá-lo volto a conseguir editar/adicionar meus produtos. Detalhe que isso não acontece nas versões anteriores. Então voltei pra versão 2.1 e está normal novamente, claro com os detalhes dos bugs anteriores.

Estou à disposição para passar mais informações caso necessário. Obrigado.

**Comment by henriqueccruz** [comment]
Olá @alexjuniordev 
Obrigado por relatar
Foi efeito colateral de uma das implementações da última versão.
Agora nosso box com informações sobre o boleto/PIX só é mostrado nos pedidos feitos com PagHiper.

Update resolvendo o problema relatado ja está disponível (v2.1.3)
