### ISSUE TITLE
Fatal Erros

### ISSUE THREAD

**Issue by alexjuniordev** [paghiper/woocommerce-paghiper#45]
Olá pessoal, tenho recebido esse erro constante. Alguém pode me ajudar a identificar o que significa? Obrigado.

2021-02-10T18:07:42+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Product_Simple::get_payment_method() in /home/lojalogincom/public_html/wp-content/plugins/woocommerce-paghiper-2.1.3/woocommerce-paghiper.php:440
Stack trace:
#0 /home/lojalogincom/public_html/wp-includes/class-wp-hook.php(289): WC_Paghiper->attach_billet(Array, 'low_stock', Object(WC_Product_Simple))
#1 /home/lojalogincom/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
#2 /home/lojalogincom/public_html/wp-content/plugins/woocommerce/includes/class-wc-emails.php(638): apply_filters('woocommerce_ema...', Array, 'low_stock', Object(WC_Product_Simple), NULL)
#3 /home/lojalogincom/public_html/wp-includes/class-wp-hook.php(287): WC_Emails->low_stock(Object(WC_Product_Simple))
#4 /home/lojalogincom/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /home/lojalogincom/public_html/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#6 /home/lojalogincom/public_html/wp-content/plugins/woocommerce/includes/cla, em /home/lojalogincom/public_html/wp-content/plugins/woocommerce-paghiper-2.1.3/woocommerce-paghiper.php, na linha 440

**Comment by kxmndev** [comment]
Mesmo problema no front retorna para o usuário "Internal Server Error"

**Comment by henriqueccruz** [comment]
@alexjuniordev - Corrigimos esse problema na versão v2.1.4
Deve estar disponível pra atualização em 1h +/-

--

@kxmndev - Sobre o seu caso, consegue nos dizer o que consta nos logs? Eles ficam em WooCommerce > Status > Logs
Qualquer linha (seguida de seu conteúdo) que contenha FATAL ERROR é interessante. Me parece que seu caso é um pouco diferente do caso relatado no primeiro post.

**Comment by henriqueccruz** [comment]
Atualização publicada
Vou manter o ticket aberto aguardando retorno do @kxmndev

**Comment by alexjuniordev** [comment]
@henriqueccruz percebi que meu ecommerce estava duplicando pedidos mesmo para outras formas de pagamento, como a de cartão de crédito... vc acha que o plugin de vocês teve algo a ver com isso? Só pra eu ficar mais tranquilo mesmo sabendo onde estava o problema

**Comment by henriqueccruz** [comment]
@alexjuniordev 
Sobre a duplicação dos pedidos, consegue me explicar um pouco melhor?
Não tenho certeza se entendi.

**Comment by kxmndev** [comment]
@henriqueccruz Tenho certeza que é o mesmo problema. Eu observei a mesma mensagem de erro do Alex no meu log do Nginx que se trata do mesmo erro na mesma linha: `Call to undefined method WC_Product_Simple::get_payment_method()`. Até por isso não abri outro ticket.

Vou testar agora a v 2.1.4 e volto para dar posição.

**Comment by alexjuniordev** [comment]
@kxmndev parece que por aqui corrigiu isso com a nova atualização. Quando puder passe um feedback se melhorou aí também. Vlw.

**Comment by kxmndev** [comment]
@henriqueccruz @alexjuniordev Funcionou ok. No log do servidor parou de ocorrer o erro. No log do WooCommerce não há nada que indique erro, apenas transação normal.

Muito obrigado!

**Comment by henriqueccruz** [comment]
Legal. Obrigado pela paciência.
Seguimos atentos ao feedback dos usuários e pedidos de suporte, melhorando a integração e experiência geral, tanto do usuário quanto do lojista.

Aproveitando, seria legal se vocês puderem deixar uma avaliação sobre o plug-in no repositório oficial do Wordpress.
https://wordpress.org/support/plugin/woo-boleto-paghiper/reviews/#new-post

Fechando este ticket, ja que o problema relatado foi resolvido.
Obrigado!
