### ISSUE TITLE
Gerar link ou PDF para pagamento em e-mail personalizado

### ISSUE THREAD

**Issue by leticiagubrov** [paghiper/woocommerce-paghiper#47]
Oi, pessoal!

Eu preciso de uma ajudinha, não manjo muito de PHP, mas estou aprendendo aos poucos.

Eu tenho um e-mail personalizado para um determinado produto, e eu preciso que esse e-mail contenha o PDF/BOLETO em anexo ou no corpo.

Como faço para conseguir enviar o boleto do pedido em um e-mail que não é padrão do WooCommerce?

Agradeço demais a ajuda!

**Comment by henriqueccruz** [comment]
Boa tarde @leticiagubrov 

Você teria algum exemplo de como esse envio é feito? Usou algum plugin para agendar esse envio?
Ou está usando ações/filtros pra tal? Seria legal você colar um trechinho da sua lógica pra te ajudarmos melhor.
Existem vários meios de se alcançar esse resultado.

**Comment by henriqueccruz** [comment]
Fechando este ticket ja que não houve interação.
Caso queira retomar, abra novo ticket por gentileza
