### ISSUE TITLE
Erro no Plugin

### ISSUE THREAD

**Issue by THALES-88** [paghiper/woocommerce-paghiper#48]
Eu estou recebendo essa mensagem, e apesar de ser possível prosseguir com o plugin, a mensagem fica aparecendo para o cliente...
Qual solução sugerem?
Notice: order_key foi chamada incorretamente. Order properties should not be accessed directly. Backtrace: require('wp-admin/edit-form-advanced.php'), do_meta_boxes, WC_Paghiper_Admin->metabox_content, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Leia como Depurar o WordPress para mais informações. (Esta mensagem foi adicionada na versão 3.0.) in /home/quatroladosquadros.com.br/public_html/wp-includes/functions.php on line 5311

**Comment by henriqueccruz** [comment]
Olá @THALES-88 
Esse tipo de mensagem não é considerada erro (é apenas um notice) e indica que a constante WP_DEBUG está setada como TRUE no seu arquivo de configuração. É má prática manter a configuração assim em sites disponíveis ao público.

De qualquer maneira, lançamos uma update que resolve esse notice.
Caso precise de suporte com alguma outra questão, peço a gentileza de abrir outro ticket.

Obrigado!
