### ISSUE TITLE
Pedido não aparece no site

### ISSUE THREAD

**Issue by rvfaelo** [paghiper/woocommerce-paghiper#5]
Acontece dois erros, na verdade.
O primeiro é que quando o cliente faz um pedido, não está aparecendo no site do PagHiper, mas eu vejo no WooCommerce. E se o cliente pagar e não constar no PagHiper, o que eu faço?

O segundo é que sempre que tento instalar a última versão do plugin, acontece isso http://prntscr.com/gjek4s

Aguardo resposta!
Obrigado e parabens pelo plugin! <3

**Comment by henriqueccruz** [comment]
Olá @rvfaelo,
O boleto é emitido no momento em que o cliente acessa o boleto, por isso não aparece quando o pedido é realizado. No momento em que ele acessar o boleto, ele aparecerá no painel da PagHiper também. Caso isso não aconteça, por favor abra outro ticket de suporte para acompanharmos e te ajudarmos com isso.

O segundo problema acabou de ser resolvido na versão 1.2.3.
Basta atualizar o plug-in.

Obrigado!
