### ISSUE TITLE
Problema na criação de pedidos

### ISSUE THREAD

**Issue by Repczuk** [paghiper/woocommerce-paghiper#56]
Olá pessoal, tudo bem?

Estou enfrentando um problema com minha loja e o plugin! Notei que os clientes precisam atualizar a página no checkout, e clicar novamente no botão de gerar pedido! Por algum motivo rola algum erro desconhecido, e o status do pedido fica como "Pagamento Pendente" até ele realizar essa ação.

Consegue dar uma olhada no site? https://hilljack.com.br/

Muito obrigado de antemão!
Victor

**Comment by henriqueccruz** [comment]
Olá @Repczuk , boa tarde
O erro ainda persiste? Confirma pra gente por favor, qual versão do plug-in está ativa na sua loja e qual versão do Wordpress está usando.

Aguardamos seu retorno.
