### ISSUE TITLE
Mensagem de Fatal errors

### ISSUE THREAD

**Issue by alexjuniordev** [paghiper/woocommerce-paghiper#58]
2021-08-12T12:43:52+00:00 CRITICAL Uncaught Exception: Pedido inválido. in /var/www/html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:104
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read()
#1 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(114): WC_Data_Store->read()
#2 /var/www/html/wp-content/plugins/woo-boleto-paghiper/includes/wc-paghiper-notification.php(21): WC_Abstract_Order->__construct()
#3 /var/www/html/wp-content/plugins/woo-boleto-paghiper/includes/wc-paghiper-notification.php(129): woocommerce_paghiper_valid_ipn_request()
#4 /var/www/html/wp-includes/class-wp-hook.php(292): woocommerce_paghiper_check_ipn_response()
#5 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#6 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#7 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php(161): do_action()
#8 /var/www/h, em /var/www/html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php, na linha 104

**Comment by henriqueccruz** [comment]
#57 

Olá @alexjuniordev , boa tarde.
Normalmente esse problema se dá quando o ID do pedido está sendo manipulado por algum outro plugin, ou o pedido é apagado antes de algum tipo de notificação enviada pela API da PagHiper.

Em qual momento essa mensagem de erro aparece para você? Aparentemente ela vem de um log.
Caso esse problema aconteça no momento da emissão, poderia nos mandar uma lista de plug-ins ativos na loja?

**Comment by dfvascao** [comment]
Boa tarde @henriqueccruz !

Poderia entrar em contato comigo no meu email por favor? dfvascao1@gmail.com 

Obrigado e no aguardo
