### ISSUE TITLE
Boleto não aparece ao realizar compra na loja

### ISSUE THREAD

**Issue by ediluz1991** [paghiper/woocommerce-paghiper#7]
Quando realizo a compra de um produto em minha loja, ao clicar no botão de "Pagar o boleto" abre uma página em branco. Gostaria de uma solução ou dica para os boletos serem impressos na tela do site.

**Comment by henriqueccruz** [comment]
Olá Ediluz, boa tarde.
Me passe mais alguns detalhes por favor. Consegue ativar a opção de debug no wp-config.php pra pegarmos mais alguns detalhes?

Se puder me falar sua versão do plug-in, Wordpress e Woocommerce, tbm ajuda.

**Comment by ediluz1991** [comment]
Segue abaixo:
lojamimodosbichos.com.br
versao paghiper: 1.2
wordpress: 4.8.1
woocommerce: 3.1.2
Realiza uma compra de teste para ver.

**Comment by henriqueccruz** [comment]
Tem a opção debug, ou debug log ativada?

**Comment by ediluz1991** [comment]
Eu ativei pelo wP-config

**Comment by henriqueccruz** [comment]
Checa se seu php.ini tem uma configuração chamada "open_basedir".
Se sim, remova (ou desative) open_basedir, ja que isso interfere no funcionamento da extensão cURL no PHP.

`open_basedir = none`

**Comment by ediluz1991** [comment]
Aparece assim:
; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file. This directive is
; *NOT* affected by whether Safe Mode is turned On or Off.
; http://php.net/open-basedir
;open_basedir =

**Comment by henriqueccruz** [comment]
Checa se não tem outro php.ini dentro da pasta do woocommerce ou na raiz do site. Se não, preenche essa opção como no comentário acima, deve resolver o problema.

**Comment by ediluz1991** [comment]
Fiz isso e ainda gera o erro.
vou deixar meu gtalk caso facilite: ediluz1991@gmail.com

**Comment by ediluz1991** [comment]
Não achei outro php.ini

**Comment by ediluz1991** [comment]
alguma outra orientação?

**Comment by henriqueccruz** [comment]
Te mandei um e-mail, @ediluz1991.

**Comment by ediluz1991** [comment]
Não recebi ainda, meu e-mail é ediluz1991@gmail.com

**Comment by henriqueccruz** [comment]
Checa na pasta de spam por favor.

**Comment by fernandoRj** [comment]
alguem pode me ajudar? erro aqui igual ao dele, clico em gerar boleto e n acontece nada

**Comment by ofmarconi** [comment]
Solução?
