### ISSUE TITLE
Falha ao gerar o pix/boleto na retentativa

### ISSUE THREAD

**Issue by davidplima** [paghiper/woocommerce-paghiper#81]
Prezado suporte do plugin PagHiper para WooCommerce,

Espero que esta mensagem o encontre bem. Estou escrevendo para solicitar a correção de um problema que tenho enfrentado ao utilizar o plugin PagHiper em minha loja virtual WooCommerce.

O erro ocorre quando um cliente tenta efetuar um pagamento através de cartão ou qualquer outra forma de pagamento, e a transação é negada. Nesse caso, o pedido é marcado como malsucedido no WooCommerce, e o cliente tem a opção de tentar pagar novamente acessando o botão de pagamento em seu painel.

Entretanto, se o cliente opta por escolher o PIX ou boleto bancário do PagHiper como método de pagamento, o plugin não gera o respectivo PIX ou boleto e exibe a mensagem "Não foi possível gerar o PIX". Isso tem causado transtornos aos nossos clientes e afetado nossas vendas.

Gostaria de solicitar a correção dessa falha o mais breve possível para garantir uma experiência de compra mais fluida e eficiente aos nossos clientes. 

Agradeço antecipadamente pela sua atenção e colaboração. Fico no aguardo de uma resposta.

**Comment by henriqueccruz** [comment]
Olá @davidplima , boa noite.
Acabamos de publicar um update que aborda, dentre outros assuntos, também a questão apresentada.
Vamos fechar este ticket e pedimos que, caso o problema persista, abra novo ticket descrevendo seu problema.

Obrigado!
