### ISSUE TITLE
Não gerar pix e boleto na tela

### ISSUE THREAD

**Issue by ojosejefferson** [paghiper/woocommerce-paghiper#83]
Olá estou usando o plugin na loja da empresa e não está gerando boleto/pix na tela para o usuario vai para o e-mail, fica meio confuso por que não aparece uma mensagem que foi enviado para o e-mail, outra coisa  é um erro que dá se o usuario não efetuou o pagamento e quando vai visualizar o pedido na sua conta aparece um erro que vem do plugin.

**Comment by henriqueccruz** [comment]
Olá @ojosejefferson , boa tarde
Poderia colar aqui a mensagem de erro que você vê ao visualizar o pedido na conta?

**Comment by henriqueccruz** [comment]
Vou fechar esse ticket por inatividade.
Caso o problema persista, por favor abra novo ticket
Estamos a disposição para ajudá-lo
