### ISSUE TITLE
erro no final da compra ao clicar em gerar boleto nada acontece

### ISSUE THREAD

**Issue by fernandoRj** [paghiper/woocommerce-paghiper#9]
instalei o plugin aqui td certinho no final de todos os processos quando vc preenche os campos de nome,emai,cpf e telefone eu clico em gerar boleto e nao acontece nada, baixei o plugin desse link do github nao consigo arrumar isso de jeito nenhum alguem pode me ajudar?

**Comment by henriqueccruz** [comment]
Ao clicar em "Pagar o Boleto", o que acontece? Tela branca?

**Comment by henriqueccruz** [comment]
Por gentileza, abra novo ticket caso queira prosseguir com o suporte.

**Comment by ofmarconi** [comment]
Isso, fica tela branca
